---
spring:
  datasource:
    url: jdbc:h2:mem
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    show_sql: false
  profiles:
    active: mock
server:
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
  context-path: /api